"""empty message

Revision ID: 33907a960a5e
Revises: 36b93d81ad60
Create Date: 2015-03-04 12:25:42.313238

"""

# revision identifiers, used by Alembic.
revision = '33907a960a5e'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Votjech', sa.String(), nullable=False),
    sa.Column('Hahn', sa.String(), nullable=False),
    sa.Column('Muz', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Hahn', 'loguser', ['Hahn'], unique=False)
    op.create_table('karty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cislo_karty', sa.String(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=False),
    sa.Column('WTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_karty'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_karty_Time', 'karty', ['Time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_karty_Time', table_name='karty')
    op.drop_table('karty')
    op.drop_index('ix_loguser_Hahn', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
